# Generated by Django 3.1.4 on 2020-12-27 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_post_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('weight', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Package',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productioncountry', models.TextField()),
                ('price', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('term', models.DateTimeField()),
                ('delivery', models.TextField()),
                ('deliverycost', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.product')),
            ],
            options={
                'verbose_name_plural': 'Trade',
            },
        ),
    ]
