# Generated by Django 3.1.4 on 2020-12-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20201227_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='opinionss',
            new_name='opinions',
        ),
    ]
